#Voxel Game Settings
#Wed Mar 25 00:10:08 TRT 2026
fov=70
keybind.BREAK_BLOCK=1000
keybind.JUMP=32
keybind.MOVE_BACKWARD=83
keybind.MOVE_FORWARD=87
keybind.MOVE_LEFT=65
keybind.MOVE_RIGHT=68
keybind.OPEN_CHAT=257
keybind.PLACE_BLOCK=1001
keybind.TOGGLE_FREECAM=70
mouseSensitivity=1.0000001
renderDistance=16
theme=dark
username=Snoxyro
vsync=true
windowMode=WINDOWED
